spring:
  # 配置文件上传大小限制
  servlet:
#    单次最大上传1G
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

# minio 参数配置
minio:
  endpoint: http://1.15.30.232:9000
  accessKey: minio
  secretKey: minio123